
# environment variables
environment:
  nodejs_version: "6"

# scripts that run after cloning repository
install:
  # install node 
  - ps: Install-Product node $Env:nodejs_version
  - npm install -g npm
  - npm install -g webpack
  - dotnet restore  
  
# scripts to run before build
before_build:
  # install node modules
after_build:
  - dotnet publish src\CoreWebApplication1 --output %appveyor_build_folder%\dist
  - cd %APPVEYOR_BUILD_FOLDER%
  - npm install
  # run webpack with production flag
  - webpack -p
  
artifacts:
  - path:  %APPVEYOR_BUILD_FOLDER%/wwwroot